# Generated by Django 5.0.7 on 2024-10-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('OPTIONAL', 'Optional')], default='NORMAL', max_length=50),
        ),
    ]
